**데이터처리1_numpy3**

Numpy Array의 연산 (1)

* Ufuncs
* 취합 연산
* 브로드캐스팅 연산

In [ ]:
import numpy as np

##1. Ufuncs## 

**1-1 Numpy와 Ufuncs**

Numpy에는 단일 종류의 값이 들어가 있음

-> 매번 타입을 체크할 필요 X, 연산에만 집중하면 됨

Ufuncs : Numpy에서 제공하는 연산 메커니즘

* 배열 내의 숫자에 대하여 효율적인 연산 수행을 목표로 함
* 마치 컴파일 한 것처럼, 타입 체크를 건너뛰고 수치 연산을 수행

    Ufunc의 적용 유형

        - Array와 Scalar
        - Array와 Array
        - 다차원 배열에도 적용 가능

**1-2 Ufuncs 연산자 종류**

파이썬 기본문법에서 제공되는 연산자와 호환됨

In [ ]:
x = np.arange(4)
print(x)
print(np.negative(x))
print(np.add(x, 5))
print(np.subtract(x, 5))
print(np.multiply(x, 2))
print(np.power(x, 2))
print(np.divide(x, 2))
print(np.floor_divide(x, 2))
print(np.mod(x, 2))

[0 1 2 3]
[ 0 -1 -2 -3]
[5 6 7 8]
[-5 -4 -3 -2]
[0 2 4 6]
[0 1 4 9]
[0.  0.5 1.  1.5]
[0 0 1 1]
[0 1 0 1]


In [ ]:
print("x = ", x)
print("-x = ", -x)
print("x + 5 = ", x+5)
print("x - 5 = ", x-5)
print("x * 2 = ", x*2) #곱하기
print("x ** 2 = ", x**2) #제곱
print("x / 2 = ", x/2) #나누기
print("x // x = ", x//2) #몫
print("x % 2 = ", x%2) #나머지

x =  [0 1 2 3]
-x =  [ 0 -1 -2 -3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x ** 2 =  [0 1 4 9]
x / 2 =  [0.  0.5 1.  1.5]
x // x =  [0 0 1 1]
x % 2 =  [0 1 0 1]


그 외 연산자 - 절대값

In [ ]:
x = np.array([-2, -1, 0, 1, 2])

In [ ]:
abs(x)

array([2, 1, 0, 1, 2])

In [ ]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [ ]:
y = np.array([3-4j, 4-3j, 2+0j, 0+1j])

In [ ]:
np.abs(y)

array([5., 5., 2., 1.])

그 외 연산자 - 삼각함수

In [ ]:
theta = np.linspace(0, np.pi, 3)

In [ ]:
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cons(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cons(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


그 외 연산자 - 지수함수

In [ ]:
x = [1, 2, 3]

In [ ]:
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3, x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [ ]:
x = [1, 2,  4, 10]

In [ ]:
print("x = ", x)
print("ln(x) = ", np.log(x))
print("ln(x) = ", np.log2(x))
print("ln(x) = ", np.log10(x))

x =  [1, 2, 4, 10]
ln(x) =  [0.         0.69314718 1.38629436 2.30258509]
ln(x) =  [0.         1.         2.         3.32192809]
ln(x) =  [0.         0.30103    0.60205999 1.        ]


**1-3 연산의 결과를 다른 배열에 저장**

Ufunc의 연산 결과 -> 새로운 배열을 하나 만들어냄

만약 연산결과를 바로 다른 변수에 저장할 수 있다면 메모리 절약 가능!

        out = 변수명

In [ ]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [ ]:
y = np.zeros(10)
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.power(2, x, out=y[::2])
print(y)

[ 2.  0.  4.  0.  8.  0. 16.  0. 32.  0.]


**1-4 Agrregate 연산**

reduce : 배열을 구성하는 모든 값에 대하여 동일한 연산을 연속으로 수행

In [ ]:
x = np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [ ]:
np.add.reduce(x)

15

In [ ]:
np.multiply.reduce(x)

120

In [ ]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [ ]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

##2. 취합 연산##

데이터로부터 취합된 통계량을 계산하는 방법

        합계, 평균, 분산, 최댓값, 최솟값, 사분위수, 중앙값, ...

**2-1 최댓값, 최솟값**

In [ ]:
big_array = np.random.random((5))
big_array

array([0.82647021, 0.57262965, 0.65851786, 0.6484565 , 0.73915072])

In [ ]:
np.max(big_array), np.min(big_array)

(0.8264702127423496, 0.5726296511025347)

**2-2 다차원 행렬에서의 취합연산**

In [ ]:
M = np.random.random((3,4))
M

array([[0.10797321, 0.58991423, 0.20174949, 0.78252169],
       [0.31238216, 0.54234152, 0.59003537, 0.1135907 ],
       [0.34789971, 0.49389434, 0.32017908, 0.40023423]])

In [ ]:
M.min(axis=0) #행 방향 연산(위에서 아래로)

array([0.10797321, 0.49389434, 0.20174949, 0.1135907 ])

In [ ]:
M.max(axis=1) #행 방향 연산 (왼쪽에서 오른쪽으로)

array([0.78252169, 0.59003537, 0.49389434])

**2-3 취합 연산 종류**

In [ ]:
x = np.arange(10)

In [ ]:
print("x = ",x)
print("sum = ", np.sum(x))
print("product = ", np.prod(x))
print("mean = ", np.mean(x))
print("standard = ", np.std(x))
print("variance = ", np.var(x))
print("minimum = ", np.min(x))
print("maximum = ", np.max(x))
print("index of minimum value = ", np.argmin(x))
print("index of maximum value = ", np.argmax(x))
print("median = ", np.median(x))
print("rank-based statistics = ", np.percentile(x, 0.5))
print("any elements are ",np.any(x))
print("all elements are ",np.all(x))

x =  [0 1 2 3 4 5 6 7 8 9]
sum =  45
product =  0
mean =  4.5
standard =  2.8722813232690143
variance =  8.25
minimum =  0
maximum =  9
index of minimum value =  0
index of maximum value =  9
median =  4.5
rank-based statistics =  0.045
any elements are  True
all elements are  False


##3.브로드캐스팅 연산##

서로 다른 차원을 가진 행렬 데이터 사이의 연산이 가능하도록 정해놓은 일종의 규칙

**3-1 브로드캐스팅 예시**

In [ ]:
#단순 행렬로 계산
a = np.array([0,1,2])
b = np.array([5,5,5])
a + b

array([5, 6, 7])

In [ ]:
#브로드캐스팅
a + 5

array([5, 6, 7])

-

In [ ]:
M = np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

-

In [ ]:
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [ ]:
a + b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

**3-2 브로드캐스팅 규칙**

* 규칙 1

        한 배열이 다른 배열에 비해 적은 차원의 수를 가지고 있다면, 적은 차원을 가진 배열이 같은 차원을 가질 수 있도록 바꾼다.
        새로운 차원을 추가할 때는 왼쪽에 1이 들어가도록 한다.

* 규칙 2

        두 배열의 차원이 같아졌는데, 서로 모양이 다르다면 모양이 같도록 바꾸어준다.

* 규칙 3

        차원이나 모양이 모두 다르다면 브로드캐스팅을 수행할 수 없다.


In [ ]:
x = np.linspace(0,5,50)
y = np.linspace(0,5,50)[:, np.newaxis]

z = np.sin(x) ** 10 + np.cos(10 + y * x) * np.cos(x)

In [ ]:
z

array([[-0.83907153, -0.83470697, -0.8216586 , ...,  0.8956708 ,
         0.68617261,  0.41940746],
       [-0.83907153, -0.82902677, -0.8103873 , ...,  0.92522407,
         0.75321348,  0.52508175],
       [-0.83907153, -0.82325668, -0.79876457, ...,  0.96427357,
         0.84172689,  0.66446403],
       ...,
       [-0.83907153, -0.48233077, -0.01646558, ...,  0.96449925,
         0.75196531,  0.41982581],
       [-0.83907153, -0.47324558,  0.00392612, ...,  0.92542163,
         0.68540362,  0.37440839],
       [-0.83907153, -0.46410908,  0.02431613, ...,  0.89579384,
         0.65690314,  0.40107702]])