**데이터처리1_numpy2**

Numpy 배열의 생성 및 변형

In [ ]:
import numpy as np

##1. 배열의 접근과 수정##

**1-1 Scratch를 통한 배열 생성**

* Numpy Array는 일종의 객체
* 생성된 데이터에 대한 다양한 정보를 attribute로 가짐

In [ ]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,4,5))

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

* 배열의 차원, 모양, 크기, 데이터 타입 등을 attribute에 지님

In [ ]:
print("x3 ndim", x3.ndim) #차원
print("x3 shape", x3.shape) #모양
print("x3 size", x3.size) #데이터 개수

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60


**1-2 배열 값에 접근**

index를 사용하여 접근 가능

In [ ]:
x1

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[2]

3

In [ ]:
x1[-1]

9

In [ ]:
x1[-2]

7

다차원 배열 -> comma seperated tuple로 접근

In [ ]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
#파이썬에서 다차원 배열에 접근하는 법
x2[0][0]

3

In [ ]:
x2[1,2]

8

In [ ]:
x2[2, -1]

7

In [ ]:
x2[-1, 0]

1

In [ ]:
x2[-1,-3]

6

In [ ]:
#다차원 배열의 수정
x2[0,0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[0,1] = 3.141592
x2 #Numpy 배열은 정적 타입! -> 타입 에러시 casting 발생

array([[12,  3,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

##2. 배열 슬라이싱과 copy##

**2-1 배열 슬라이싱**

배열의 부분을 슬라이싱하여 사용 가능

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5] # x[:n] index 0부터 n-1까지 n개 슬라이싱

array([0, 1, 2, 3, 4])

In [ ]:
x[5:] # x[:n] index n부터 끝까지 슬라이싱

array([5, 6, 7, 8, 9])

In [ ]:
x[4:7] # x[p:q] index p부터 q-1까지 슬라이싱

array([4, 5, 6])

배열을 건너뛰면서 슬라이싱 가능

In [ ]:
x[::2] # x[::n] n개씩 건너뛰면서 슬라이싱

array([0, 2, 4, 6, 8])

In [ ]:
x[1::2] # x[p::q] index p부터 오른쪽으로 q개씩 건너뛰면서 슬라이싱

array([1, 3, 5, 7, 9])

In [ ]:
x[1:9:2]

array([1, 3, 5, 7])

왼쪽으로 건너뛰면서 슬라이싱 가능

In [ ]:
x[::-1] #좌우반전

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
x[5::-2] #x[p::-q] index p부터 왼쪽으로 q개씩 건너뛰면서 슬라이싱

array([5, 3, 1])

**2-2 다차원 배열의 슬라이싱**

* 2차원 배열 x에 대하여 
        x[a:b:c, d:e:f]
        : a행부터 b-1행까지 c개씩 건너뛰면서 슬라이싱
         d열부터 e-1열까지 f개씩 건너뛰면서 슬라이싱


In [ ]:
x2

array([[12,  3,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2[:2, :3] # x[:p, :q] p개행 q개열씩 슬라이싱

array([[12,  3,  2],
       [ 7,  6,  8]])

In [ ]:
x2[:3, ::2] # x[:p, ::q] p개행, 열은 q개씩 건너뛰면서 슬라이싱

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [ ]:
x2[::-1, ::-1] #좌우반전

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  3, 12]])

* 행, 열 추려내기

In [ ]:
print(x2[:,0]) #first column

[12  7  1]


In [ ]:
print(x2[:,1]) #second column

[3 6 6]


In [ ]:
print(x2[0, :]) #first row

[12  3  2  4]


In [ ]:
print(x2[2, :]) #third row

[1 6 7 7]


In [ ]:
print(x2[0])

[12  3  2  4]


**2-3 Copy**

No-copy 특성

* 슬라이싱 된 결과값

        기존 방식 : 복사된 새로운 데이터
        Numpy : 원본 데이터에 대한 접근을 유지

In [ ]:
x2

array([[12,  3,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [ ]:
x2_sub = x2[:2, :2] #2개행, 2개열 슬라이싱
x2_sub

array([[12,  3],
       [ 7,  6]])

In [ ]:
x2_sub[0,0] = 45
x2_sub

array([[45,  3],
       [ 7,  6]])

In [ ]:
x2

array([[45,  3,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

copy를 이용한 복사본 데이터 생성

In [ ]:
x2_sub_copy = x2[:2, :2].copy()
x2_sub_copy

array([[45,  3],
       [ 7,  6]])

In [ ]:
x2_sub_copy[0,0] = 97
x2_sub_copy

array([[97,  3],
       [ 7,  6]])

In [ ]:
x2

array([[45,  3,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

## 3. 배열의 형태 변화##

**3-1 데이터의 reshaping**

reshaping : 데이터를 구성하는 차원의 모양을 변경

(예시 : 1차원 데이터(9,)를 2차원 (3,3) 행렬로 변환)

In [ ]:
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**3-2 1차원 벡터의 2차원 표현**

* 1차원 벡터(n,)를 2차원의 행 matrix(1,n)로 표현

In [ ]:
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [ ]:
x.reshape(1,3).ndim #2차원

2

* 1차원 벡터(n,)를 2차원의 열 matrix(n,1)로 표현

In [ ]:
x.reshape((3,1))

array([[1],
       [2],
       [3]])

reshape 할 때 사용되는 패러미터


In [ ]:
x.reshape(1,-1) #-1은 reshape할 때 알아서 채우라는 뜻

array([[1, 2, 3]])

In [ ]:
x.reshape(-1,1) #1열은 확실하고 -1은 알아서 채워라

array([[1],
       [2],
       [3]])

In [ ]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [ ]:
x[np.newaxis, :]

array([[1, 2, 3]])

**3-3 배열 붙이기**

배열 붙이기 : np.concatenate 사용

1차원 배열의 붙이기

In [ ]:
x = np.array([1,2,3])
y = np.array([4,5,6])
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  4,  5,  6, 99, 99, 99])

다차원 배열의 붙이기

* 2차원일 경우

        axis = 0 -> 행 방향으로 붙이기 (위에서 아래로)
        axis = 1 -> 열 방향으로 붙이기 (왼쪽에서 오른쪽으로)

In [ ]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid,grid]) #행방향

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.concatenate([grid,grid], axis=1) #열방향

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

* 두 배열의 차원이 다를 경우

        vstack(vertical stack) : 위에서 아래로
        hstack(horizontal stack) : 왼쪽에서 오른쪽으로

In [ ]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [ ]:
y = np.array([[99],[9]])

np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4,  9]])

**3-4 배열 나누기**

np.split 사용

In [ ]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5]) #index 3 앞에서 한 번, 5 앞에서 한 번 나누기
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [ ]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

np.vsplit : 행을 기준으로 끊기 (가로)

np.hsplit : 열을 기준으로 끊기 (세로)

In [ ]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
left, right = np. hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
