**데이터처리1_numpy1**

Python의 Numpy library를 이용한 수치 데이터의 표현 및 처리


##1. numpy 소개##

**1-1 데이터 형태**

* tabular data : 엑셀로 나타내지는 데이터

    열과 행의 이차원의 형태로 표현 가능

* text data : 단어의 순서들로 구성되어 있는 문장

* image data
 
* 동영상 : image data 여러개를 순서대로 모아 실행


* numerical Arrays 수치형 배열 

  : Scalars, Vectors(1차원), Matrices(2차원) & Tensors(3차원)
  
  → 숫자 여러개가 모여 하나의 의미를 구성

    멀티 미디어 데이터들을 수치형 배열로 전환하여 분석 및 처리
    
    다양한 종류의 데이터 표현의 처리의 근간이 됨
        (ex) 이미지 데이터 → 픽셀값으로 구성된 2차원 행렬로 표현 가능
             텍스트 데이터 → 문장을 구성하는 단어의 출현여부를 기록한 벡터로 표현 가능

**1-2 선형대수**

* 공학적인 문제를 행렬의 형태로 정의하고 그 해답을 구하는 과정과 방법
* 산업공학 전반에 사용되는 기법의 근간이 됨
    
        최적화, 통계, 머신러닝 등

##2. numpy의 특성과 이해##

**2-1 Python 문법의 특징**

Numpy 모듈 불러오기

* import numpy as np 

In [ ]:
import numpy as np

Scalar : 숫자값

    a = 3

1차원 vector : 리스트를 이용
    
    a = [1,2,3,4,5]

2차원 matrix

    a = [[1,2,3], [4,5,6]]

* Statically-typed language (정적) : 변수 생성시 저장할 데이터의 종류를 명시적으로 선언하는 언어
* Dynamically-typed language (동적) : 변수 생성시 알아서 입력되는 값의 종류를 추론

  **→ Python은 Dynamically-typed language**
  
  서로 다른 종류의 값으로 구성된 리스트를 동적으로 생성 가능
  
  **but** 값을 추론하는 데 시간 소요 > 효율성 떨어짐
  

In [ ]:
L = [1, 'a', 3, 2.5, "c"]
for i in L:
  print(type(i))

<class 'int'>
<class 'str'>
<class 'int'>
<class 'float'>
<class 'str'>


**2-2 Fixed-type Array를 만드는 방법**

in Python

파이썬 3.3 이후 > 같은 타입을 가진 array 생성 가능

In [ ]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

using Numpy

* Numpy array 라이브러리를 사용하면 fixed type array를 더욱 효과적으로 만들 수 있음!

        casting : 데이터의 타입을 변경
        upcasting (int -> float)

In [ ]:
#파이썬 리스트로부터 integer array 생성
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
type([1, 4, 2, 5, 3])

list

In [ ]:
type(np.array([1, 4, 2, 5, 3]))

numpy.ndarray

In [ ]:
#Numpy안에는 같은 종류의 같이 들어오도록 강제 > float로 type 일치시킴
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
#타입을 강제하여 array 생성
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

2차원 list로부터 numpy array 생성 가능

In [ ]:
#다차원 리스트 -> 다차원 배열 생성 가능
np.array([[2,3,4],[4,5,6],[6,7,8]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

**2-3 Scratch를 이용한 배열 생성**

단일 값으로 구성된 array 생성

In [ ]:
np.zeros(10, dtype=int) #(shape, dtype)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
np.ones((3,5), dtype=float) #(shape, dtype)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((3,5), 3.14) 

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

interval value로 이루어진 array 생성

In [ ]:
np.arange(0,20,2) #0부터 20 미만까지 2 간격으로 배열 생성

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,1,5) #0부터 1까지 일정한 간격으로 5개의 원소를 갖는 배열 생성

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,8,5)

array([0., 2., 4., 6., 8.])

난수로 구성된 배열 생성

In [ ]:
np.random.normal(0,1,(3,3)) #평균이 0이고 표준편차가 1인 (3,3) 배열 생성

array([[-1.16369896,  0.70238861,  0.55899457],
       [-0.46513477,  0.90652905,  1.01717117],
       [-0.04948314, -0.49231834,  0.67572499]])

In [ ]:
np.random.randint(0,10,(3,3)) #0부터 10미만까지 (3,3) 정수 배열 생성

array([[6, 1, 5],
       [0, 2, 7],
       [3, 1, 6]])

그 외의 배열 생성 방법

In [ ]:
np.eye(3) #(n, n) 단위 행렬 생성

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3) #의미 없는 아무 값

array([1., 1., 1.])